name = "chatbot test"
client_id = "d93b38ee48a605c8c4d2bf93f0522755"

[access_scopes]
scopes = "read_products,write_app_proxy"

[app_proxy]
url = "/api/shopify/proxy"
prefix = "apps"
subpath = "assistant"

[webhooks]
api_version = "2026-01"

[auth]
redirect_urls = [
  "https://ai-nutritionist-v1.vercel.app/api/auth/callback"
]

[app_url]
value = "https://ai-nutritionist-v1.vercel.app/"
